css létrehozás+ linkelés
kallaigabor06/Proj1-McLaren-F1-Team-9C pull request #13
Opened 2023-02-13 10:09 UTC by szollingerrajmund

ezt is nézd meg pls

2023-02-13 12:00 UTC, kallaigabor06 requested changes
Valami conflictot resolve-olni kell

2023-02-13 12:26 UTC, szollingerrajmund commented
kész

2023-02-14 07:58 UTC, szollingerrajmund commented
le kéne mergeölnöd mert akartál rajta valamit cserélni de nézd meg elötte

2023-02-17 07:02 UTC, kallaigabor06 approved these changes
nice job

2023-02-17 07:02 UTC, merged